foreach(ARG INPUT OUTPUT ERROR)
  if(EXEC_${ARG}_FILE)
    list(APPEND EXECUTE_PROCESS_FILE_ARGS ${ARG}_FILE "${EXEC_${ARG}_FILE}")
  endif()
endforeach()

execute_process(
  COMMAND ${EXEC_COMMAND} ${EXEC_ARGS}
  ${EXECUTE_PROCESS_FILE_ARGS}
  OUTPUT_VARIABLE EXEC_PROCESS_OUTPUT
  ERROR_VARIABLE EXEC_PROCESS_OUTPUT
  RESULT_VARIABLE EXEC_RESULT
)

if(NOT (EXEC_RESULT EQUAL 0))
  message(FATAL_ERROR "${EXEC_PROCESS_OUTPUT}")
endif()

